#
# Copyright 2014 myOS Group. All rights reserved.
#

APP_NAME=ColorSpace
CFLAGS=-DDEBUG -fblocks
LDLIBS= -llog -lCoreFoundation -lFoundation -lOpenGLES -lUIKit -lCoreGraphics
OBJECTS = \
    main.o \
    AppDelegate.o \
    ColorSpaceView.o \

include ${MYOS_PATH}/android/sdk/resources/makefile-executable
