
APP_NAME=Console
#PACKAGE_ID=com.myos.console
CFLAGS=-DDEBUG -fblocks
LDLIBS= -llog -lCoreFoundation -lFoundation -lIOKit 
OBJECTS = \
    main.o \

include $(MY_FRAMEWORKS_PATH)/resources/makefile-executable
