#
# Copyright 2014 myOS Group. All rights reserved.
#

APP_NAME=Gradients
CFLAGS=-DDEBUG -fblocks
LDLIBS= -llog -lCoreFoundation -lFoundation -lOpenGLES -lUIKit -lCoreGraphics -lCoreAnimation
OBJECTS = \
    main.o \
    AppDelegate.o \
    GradientsView.o \

include ${MY_FRAMEWORKS_PATH}/resources/makefile-executable
