#
# Copyright 2014 myOS Group. All rights reserved.
#

APP_NAME=RedRectangle
CFLAGS=-DDEBUG -fblocks
LDLIBS= -llog -lCoreFoundation -lFoundation -lOpenGLES -lUIKit
OBJECTS = \
    main.o \
    AppDelegate.o \
    RRSolidView.o \

include ${MY_FRAMEWORKS_PATH}/resources/makefile-executable
