#
# Copyright 2014 myOS Group. All rights reserved.
#

APP_NAME=GrayRectangle
CFLAGS=-DDEBUG -fblocks
LDLIBS= -llog -lCoreFoundation -lFoundation -lOpenGLES -lUIKit
OBJECTS = \
    main.o \
    AppDelegate.o \
    RectangleView.o \

include ${MYOS_PATH}/android/sdk/resources/makefile-executable
